# Welcome to Jekyll!

title: Brucezz's Corner
description: Brucezz's blog.
baseurl: ""
url: "http://brucezz.itscoder.com"

timezone: Asia/Shanghai
encoding: UTF-8
permalink: /:title

github_username:  brucezz
weibo_username:  brucezzX
email: im.brucezz@gmail.com

cnzz_id: 1256702937
duoshuo_short_name: brucezz


# Default header
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
