# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Brucezz's Corner
description: Brucezz's blog.
baseurl: ""
url: "http://brucezz.itscoder.com"

timezone: Asia/Shanghai
encoding: UTF-8
permalink: /:title

github_username:  brucezz
weibo_username:  brucezzX
email: im.brucezz@gmail.com


# 默认头信息
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
